"""empty message

Revision ID: db646eb095e4
Revises: a43b9748ceee
Create Date: 2019-07-01 10:53:54.244763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db646eb095e4'
down_revision = 'a43b9748ceee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validator_role_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('requester_user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('reviewed_howto', sa.Boolean(), nullable=True),
    sa.Column('read_learnosm', sa.Boolean(), nullable=True),
    sa.Column('read_code_conduct', sa.Boolean(), nullable=True),
    sa.Column('agreed_interactions', sa.Boolean(), nullable=True),
    sa.Column('agreed_osmdata', sa.Boolean(), nullable=True),
    sa.Column('response_user_id', sa.BigInteger(), nullable=True),
    sa.Column('response_reason', sa.String(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['response_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validator_role_requests_id'), 'validator_role_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validator_role_requests_id'), table_name='validator_role_requests')
    op.drop_table('validator_role_requests')
    # ### end Alembic commands ###
